MissionskyOA.Portal/Controllers/AnnouncementController.cs
using Kendo.Mvc;
using Kendo.Mvc.UI;
using MissionskyOA.Core.Enum;
using MissionskyOA.Models;
using MissionskyOA.Portal.Common;
using MissionskyOA.Services;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MissionskyOA.Portal.Controllers
{
     [AuthorizeFilter]
    public class AnnouncementController : Controller
    {

         IAnnouncementService AnnouncementService;
        //
        // GET: /Area/

        public AnnouncementController(IAnnouncementService announcementService)
        {
            this.AnnouncementService = announcementService;
        }

        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 异步加载数据
        /// </summary>
        /// <param name="dRequest"></param>
        /// <returns></returns>
        public ActionResult Read([DataSourceRequest]DataSourceRequest dRequest)
        {
            SortModel sort = null;
            if (dRequest.Sorts != null && dRequest.Sorts.Count > 0)
            {
                sort = dRequest.Sorts[0].ToSortModel();
            }
            FilterModel filter = null;
            if (dRequest.Filters != null && dRequest.Filters.Count > 0)
            {
                filter = ((FilterDescriptor)dRequest.Filters[0]).ToSortModel();
            }
            var annocumentResult = AnnouncementService.List(dRequest.Page, dRequest.PageSize, sort, filter);
            DataSourceResult result = new DataSourceResult()
            {
                Data = annocumentResult.Data,
                Total = annocumentResult.Total
            };

            return Json(result);
        }

        /// <summary>
        /// 编辑
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Edit(int? id)
        {
            var businessTypeList = new List<SelectListItem>();
            businessTypeList.Add(new SelectListItem()
            {
                Text = "公告通知",
                Value = ((int)AnnouncementType.AdministrationEventAnnounce).ToString()
            });
            businessTypeList.Add(new SelectListItem()
            {
                Text = "资产盘点",
                Value = ((int)AnnouncementType.AssetInventory).ToString()
            });
            businessTypeList.Add(new SelectListItem()
            {
                Text = "活动消息",
                Value = ((int)AnnouncementType.ActivityMessage).ToString()
            });
            businessTypeList.Add(new SelectListItem()
            {
                Text = "公司消息",
                Value = ((int)AnnouncementType.CompanyNews).ToString()
            });
            businessTypeList.Add(new SelectListItem()
            {
                Text = "员工消息",
                Value = ((int)AnnouncementType.EmployeeeNews).ToString()
            });

            ViewData["businessTypeList"] = new SelectList(businessTypeList, "Value", "Text", "0");
            if (id.HasValue && id.Value > 0)
            {
                var model = this.AnnouncementService.GetAnnouncementByID(id.Value);
                if (model.Type != null)
                {
                    ViewData["businessTypeList"] = new SelectList(businessTypeList, "Value", "Text", (int)model.Type);

                }
                return View(model);
            }
            else
            {
                AnnouncementModel model = new AnnouncementModel();
                return View(model);
            }
        }

        /// <summary>
        /// 编辑提交
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Edit(AnnouncementModel model)
        {
            string action = Request["Submit"];
            if (action == "cancel")
            {
                return RedirectToAction("Index");
            }

            if (string.IsNullOrEmpty(model.Title))
            {
                ModelState.AddModelError("Title", "请输入标题.");
            }

            if (string.IsNullOrEmpty(model.Content))
            {
                ModelState.AddModelError("Content", "请输入通知内容.");
            }
            if (model.EffectiveDays==null ||model.EffectiveDays==0)
            {
                ModelState.AddModelError("EffectiveDays", "请输入有效天数.");
            }
            if (ModelState.IsValid)
            {
                try
                {                                   
                    var annocumentModel = new AnnouncementModel()
                    {
                        Type = model.Type,
                        Title = model.Title,
                        Content = model.Content,
                        ApplyUserId =CommonInstance.GetInstance().LoginUser.Id,
                        EffectiveDays = model.EffectiveDays,
                        CreateUserId = CommonInstance.GetInstance().LoginUser.Id,
                        CreatedTime = DateTime.Now,
                        Status = AnnouncementStatus.AllowPublish,
                        RefAssetInventoryId=0
                    };
                    this.AnnouncementService.AddAnnouncement(annocumentModel);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                 
                    ViewBag.Message = ex.Message;
                }
            }
            var businessTypeList = new List<SelectListItem>();
            businessTypeList.Add(new SelectListItem()
            {
                Text = "公告通知",
                Value = ((int)AnnouncementType.AdministrationEventAnnounce).ToString()
            });
            businessTypeList.Add(new SelectListItem()
            {
                Text = "资产盘点",
                Value = ((int)AnnouncementType.AssetInventory).ToString()
            });
            businessTypeList.Add(new SelectListItem()
            {
                Text = "活动消息",
                Value = ((int)AnnouncementType.ActivityMessage).ToString()
            });
            businessTypeList.Add(new SelectListItem()
            {
                Text = "公司消息",
                Value = ((int)AnnouncementType.CompanyNews).ToString()
            });
            businessTypeList.Add(new SelectListItem()
            {
                Text = "员工消息",
                Value = ((int)AnnouncementType.EmployeeeNews).ToString()
            });
            ViewData["businessTypeList"] = new SelectList(businessTypeList, "Value", "Text", (int)model.Type);
            return View(model);
        }

    }
}

MissionskyOA.Portal/Views/Announcement/Edit.cshtml
@using MissionskyOA.Core.Enum;

@model MissionskyOA.Models.AnnouncementModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section class="content-header">
    <h1>
        发布通告
        <small></small>
    </h1>
</section>
<section class="content">
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title"></h3>
            <div class="box-tools pull-right">
            </div>
        </div><!-- /.box-header -->
        @using (Html.BeginForm("Edit", "Announcement", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            <div class="box-body">
                <div class="form-group">
                    @Html.LabelFor(m => m.Type, "通告类型", new { @class = "col-sm-2 control-label" })
                    <div class="col-sm-3">
                        @(Html.Kendo().DropDownListFor(m => m.Type)
                            .Name("Type")
                            .BindTo(ViewData["businessTypeList"] as SelectList).DataTextField("Text")
                            .HtmlAttributes(new { style = "width:250px" })
                        )
                        @Html.ValidationMessageFor(m => m.Type)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Title, "标题", new { @class = "col-sm-2 control-label" })
                    <div class="col-sm-3">
                        @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Title)
                    </div>

                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Content, "消息内容", new { @class = "col-sm-2 control-label" })
                    <div class="col-sm-3">
                        @Html.TextAreaFor(m => m.Content, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Content)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.EffectiveDays, "有效天数", new { @class = "col-sm-2 control-label" })
                    <div class="col-sm-3">
                        @Html.TextBoxFor(m => m.EffectiveDays, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.EffectiveDays)
                    </div>
                </div><div class="form-group">
                    <div class="col-sm-2"></div>
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-default" value="cancel" name="Submit">取消</button>
                        <button type="submit" class="btn btn-info" value="save" name="Submit">提交</button>
                    </div>
                </div>
            </div><!-- /.box-body -->
            @Html.HiddenFor(m => m.Id)
        }

    </div><!-- /.box -->
</section>

<div class="modal fade modal-center" id="messageModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                <h4 class="modal-title" id="mySmallModalLabel">提示</h4>
            </div>
            <div class="modal-body">
                @ViewBag.Message
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">确认</button>
            </div>
        </div>
    </div>
</div>

@section pagescript{
    <script>
        function showMessage() {
            var message = '@(string.IsNullOrEmpty(ViewBag.Message)?"":ViewBag.Message)';
            if (message != "") {
                $('#messageModal').modal();
            }
        }
        showMessage();
    </script>
}

MissionskyOA.Portal/Views/Announcement/Index.cshtml
@using PagedList.Mvc;
@{
    ViewBag.Title = "通知列表";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section class="content-header">
    <h1>
        @ViewBag.Title
        <small></small>
    </h1>
    <div class="pull-right header-r-toolbar">
        <a class="btn btn-primary" href="@Url.Action("Edit", "Announcement")">新增</a>
    </div>
</section>
<section class="content">
    @{
        Html.Kendo().Grid<MissionskyOA.Models.AnnouncementModel>()
            .Name("grid")
            .Columns(cols =>
            {
                cols.Bound(c => c.Id).Title("#").Sortable(false).Filterable(false);
                cols.Bound(c => c.Title).Title("标题").Sortable(false).Filterable(false);
                cols.Bound(c => c.Type).Title("通告类型").Sortable(false).Filterable(false);
                cols.Bound(c => c.ApplyUserName).Title("申请人").Sortable(false).Filterable(false);
                cols.Bound(c => c.Content).Title("内容").Sortable(false).Filterable(false);
                cols.Bound(c => c.EffectiveDays).Title("有效天数").Sortable(false).Filterable(false);
                cols.Bound(c => c.Status).Title("状态").Sortable(false).Filterable(false);
                cols.Bound(c => c.CreatedTime).Format("{0:yyyy/MM/dd hh:mm:ss}").Title("创建时间").Filterable(false);
                cols.Bound(c => c.Id).Title("操作").ClientTemplate(
@"<a class='btn btn-link' href='" + @Url.Action("Edit", "Announcement", new { id = "#:Id#" }) + "'>编辑</a>").Sortable(false).Filterable(false);
            })
            .Filterable(filterable => filterable
            .Extra(false)
            .Operators(operators => operators
                .ForString(str => str.Clear()
                    .StartsWith("开头")
                    .IsEqualTo("相等")
                    .IsNotEqualTo("不相等")
                ))
            )
            .Sortable(f => f.AllowUnsort(true))
            .Pageable(pageable => pageable.Refresh(true))
            .DataSource(datasource => datasource.Ajax()
                .PageSize(10)
                .Read(read => read.Action("Read", "Announcement"))
                )
            .Render();
    }
</section>
@section pagescript{

}